#!/usr/bin/python

import pandas as pd

file=open('udpserver-1-1.txt')
line=file.readlines()

line=line[9:]
line=[i.split('\t',7)[7] for i in line]
df=pd.DataFrame(line)
df = df[0].str.strip('\n')
df.to_csv("transform.csv")

cols = list(pd.read_csv("transform.csv", nrows =1))
df = pd.read_csv("transform.csv",  usecols =[i for i in cols if i != '0'])
difference = df.diff(axis=0)
difference = difference["ArrTime"]*1000000
difference = difference.fillna(0)
difference = difference.round()
difference = difference.astype('int64')
difference.to_csv("transform.csv")

print '\n Done converting delta times for all the packets arrival times! Now run 2_run script for getting data rates.'
