#!/usr/bin/python

import csv

f = open('transform.csv', 'r')
reader = csv.reader(f)
mylist = list(reader)
f.close()
i=1
try:
    while True:
        # x=1024/int(mylist[i][1])
        x=8192
        mylist[i].append(str(x))
        mylist[i].pop(0)
        i+=1
except Exception as e:
    pass
outfile=open('./data_rates.csv','w')
writer=csv.writer(outfile)
writer.writerows(mylist)
f = open('transform.csv', 'r')
reader = csv.reader(f)
mylist_sec = list(reader)
f.close()
i=1
try:
    while True:
        y=float((int(mylist_sec[i][1]))*pow(10, -6))
        x=8192
        a="{:.6f}".format(float(y))
        mylist_sec[i].append(str(a))
        mylist_sec[i].append(str(x))
        mylist_sec[i].pop(0)
        i+=1
except Exception as e:
    pass
i=1
try:
    while True:
        mylist_sec[i].pop(0)
        i+=1
except Exception as e:
    pass
#print(mylist_sec)
outfile=open('./data_rates_sec.csv','w')
writer=csv.writer(outfile)
writer.writerows(mylist_sec)
print ('\n Done extracting data rates! Please check the data_rates.csv file')