#!/usr/bin/env python3

from matplotlib import mlab
import matplotlib.pyplot as plt
import numpy as np
import glob
import csv
import os

print ("INFO: Now creating the accuracy graphs...\n")
def graph_plot():
    x = []
    y = []
    myFiles = glob.glob('*.csv')
    a=0
    for i in range(len(myFiles)):
        with open(myFiles[a],'r') as csvfile:
            plots = csv.reader(csvfile, delimiter=',')
            for row in plots:
                #Time in us
                x.append(row[0])
                #packets in bits
                y.append(row[1])

        plt.scatter(x, y)
        plt.xlabel('seq.no')
        plt.ylabel('Inter-arrival times')
        plt.savefig(f'{myFiles[a]}.png')
        plt.locator_params(axis='y', nbins=5000)
        plt.locator_params(axis='x', nbins=5000)
        plt.clf()
        a+=1
os.chdir('convShaper2_cerberus')
p=os.listdir(os.getcwd())
c=0
for i in range(len(p)):
    try:
        os.chdir(p[c])
        c=c+1
        graph_plot()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convShaper2_convSrc3')
p=os.listdir(os.getcwd())
d=0
for i in range(len(p)):
    try:
        os.chdir(p[d])
        d+=1
        graph_plot()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convSrc3_cerberus')

p=os.listdir(os.getcwd())
e=0
for i in range(len(p)):
    try:
        os.chdir(p[e])
        e+=1
        graph_plot()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')
print("INFO: Done with the accuracy graphs, check them in the respective directories")
