#!/usr/bin/env python3

import glob
import os
import pandas as pd
import csv

print("INFO: Started calculations...\n")
def convers():
    myFiles = glob.glob('*.txt')
    a=0
    for i in range(len(myFiles)):
        file=open(myFiles[a])
        line=file.readlines()
        line=line[10:]
        line=[i.split('\t',7)[7] for i in line]
        df=pd.DataFrame(line)
        df=df[0].str.strip('\n')
        df.to_csv(f"arrival_results_{myFiles[a][:9]}.csv")
        
        cols = list(pd.read_csv(f"arrival_results_{myFiles[a][:9]}.csv", nrows =1))
        df = pd.read_csv(f"arrival_results_{myFiles[a][:9]}.csv",  usecols =[1])
        difference = df.diff(axis=0)
        difference = difference*1000
        difference = difference.round(2)
        difference = difference.astype(float)
        difference.to_csv(f"arrival_results_{myFiles[a][:9]}.csv")
        f = open(f'arrival_results_{myFiles[a][:9]}.csv', 'r')
        reader = csv.reader(f)
        mylist = list(reader)
        mylist[1]=[0,0,0,0]
        f.close()
        i=2
        try:
            while True:
                x = str(mylist[i][1])
                mylist[i].append(str(1024))
                mylist[i].append("1024 bytes / %s msec"%x)
                i+=1
        except Exception as e:
            pass
        outfile=open(f'./arrival_results_{myFiles[a][:9]}.csv','w')
        writer=csv.writer(outfile)
        writer.writerows(mylist[1:])
        a+=1
def dep_convers():
    myFiles = glob.glob('*.txt')
    a=0
    for i in range(len(myFiles)):
        file=open(myFiles[a])
        line=file.readlines()
        line=line[10:]
        line=[i.split('\t',7)[6] for i in line]
        df=pd.DataFrame(line)
        df=df[0].str.strip('\n')
        df.to_csv(f"departure_results_{myFiles[a][:9]}.csv")
        
        cols = list(pd.read_csv(f"departure_results_{myFiles[a][:9]}.csv", nrows =1))
        df = pd.read_csv(f"departure_results_{myFiles[a][:9]}.csv",  usecols =[1])
        difference = df.diff(axis=0)
        difference = difference*1000
        difference = difference.round(2)
        difference = difference.astype(float)
        difference.to_csv(f"departure_results_{myFiles[a][:9]}.csv")
        f = open(f'departure_results_{myFiles[a][:9]}.csv', 'r')
        reader = csv.reader(f)
        mylist = list(reader)
        mylist[1]=[0,0,0,0]
        f.close()
        i=2
        try:
            while True:
                x = str(mylist[i][1])
                mylist[i].append(str(1024))
                mylist[i].append("1024 bytes / %s msec"%x)
                i+=1
        except Exception as e:
            pass
        outfile=open(f'./departure_results_{myFiles[a][:9]}.csv','w')
        writer=csv.writer(outfile)
        writer.writerows(mylist[1:10000])
        a+=1
os.chdir('convShaper2_cerberus')
p=os.listdir()
c=0
for i in range(len(p)):
    try:
        os.chdir(p[c])
        c=c+1
        convers()
        dep_convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convShaper2_convSrc3')
p=os.listdir()
d=0
for i in range(len(p)):
    try:
        os.chdir(p[d])
        d+=1
        convers()
        dep_convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convSrc3_cerberus')

p=os.listdir()
e=0
for i in range(len(p)):
    try:
        os.chdir(p[e])
        e+=1
        convers()
        dep_convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')
print("INFO: Done with the calculations, check results in the respective directories\n")
