#!/usr/local/bin/python3

import glob
import os
import pandas as pd
import csv
def convers():
    #os.chdir(r'directory where the files are located')
    myFiles = glob.glob('*.txt')
    a=0
    # try:
    for i in range(len(myFiles)):
        file=open(myFiles[a])
        # print(myFiles[a][:9])
        line=file.readlines()
        # print(line)
        line=line[10:]
        line=[i.split('\t',7)[7] for i in line]
        df=pd.DataFrame(line)
        df=df[0].str.strip('\n')
        df.to_csv(f"results_{myFiles[a][:9]}.csv")
        
        cols = list(pd.read_csv(f"results_{myFiles[a][:9]}.csv", nrows =1))
        df = pd.read_csv(f"results_{myFiles[a][:9]}.csv",  usecols =[1])
        difference = df.diff(axis=0)
        difference = difference*1000000
        difference = difference.fillna(0)
        difference = difference.round()
        difference = difference.astype('int64')
        difference.to_csv(f"results_{myFiles[a][:9]}.csv")
        f = open(f'results_{myFiles[a][:9]}.csv', 'r')
        reader = csv.reader(f)
        mylist = list(reader)
        g=float(line[0])
        o=str(g)
        mylist[1]=[0,o[11:], str(1024), float(8192/int(o[11:]))]
        f.close()
        i=2
        try:
            while True:
                x=float(8192/int(mylist[i][1]))
                h="{:.6f}".format(float(x))
                mylist[i].append(str("1024"))
                mylist[i].append(str(h))
                i+=1
        except Exception as e:
            pass
        outfile=open(f'./results_{myFiles[a][:9]}.csv','w')
        writer=csv.writer(outfile)
        writer.writerows(mylist[1:])
        #print(mylist_sec)
        #print(mylist_sec)
        a+=1
    # except Exception as e:
    #     pass
    #     print ('\n Done extracting data rates! Please check the data_rates.csv file')
os.chdir('convShaper2_cerberus')
p=os.listdir()
print(p)
c=0
for i in range(len(p)):
    try:
        os.chdir(p[c])
        print(os.getcwd())
        c=c+1
        convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convShaper2_convSrc3')
p=os.listdir()
print(p)
d=0
for i in range(len(p)):
    try:
        os.chdir(p[d])
        print(os.getcwd())
        d+=1
        convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convSrc3_cerberus')

p=os.listdir()
print(p)
e=0
for i in range(len(p)):
    try:
        os.chdir(p[e])
        print(os.getcwd())
        e+=1
        convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')
    