#!/usr/local/bin/python3

import glob
import os
import pandas as pd
import csv

print("INFO: Started calculations...\n")
def convers():
    myFiles = glob.glob('*.txt')
    a=0
    for i in range(len(myFiles)):
        file=open(myFiles[a])
        line=file.readlines()
        line=line[10:]
        line=[i.split('\t',7)[7] for i in line]
        df=pd.DataFrame(line)
        df=df[0].str.strip('\n')
        df.to_csv(f"results_{myFiles[a][:9]}.csv")
        
        cols = list(pd.read_csv(f"results_{myFiles[a][:9]}.csv", nrows =1))
        df = pd.read_csv(f"results_{myFiles[a][:9]}.csv",  usecols =[1])
        difference = df.diff(axis=0)
        difference = difference*1000000
        difference = difference.fillna(0)
        difference = difference.round()
        difference = difference.astype('int64')
        difference.to_csv(f"results_{myFiles[a][:9]}.csv")
        f = open(f'results_{myFiles[a][:9]}.csv', 'r')
        reader = csv.reader(f)
        mylist = list(reader)
        bytes_to_bits=1024*8
        mylist[1]=[0,0,0,0]
        # relative_time=0
        # pkt1_arr_time=float(line[0])
        # pkt1_inter_arr_time=pkt1_arr_time-relative_time
        # pkt1_inter_arr_time=str(pkt1_inter_arr_time)
        # mylist[1]=[0,pkt1_inter_arr_time[11:], bytes_to_bits, float(8192/int(pkt1_inter_arr_time[11:]))]
        f.close()
        i=2
        try:
            while True:
                x=float(8192/int(mylist[i][1]))
                h="{:.6f}".format(float(x))
                mylist[i].append(str(bytes_to_bits))
                mylist[i].append(str(h))
                i+=1
        except Exception as e:
            pass
        outfile=open(f'./results_{myFiles[a][:9]}.csv','w')
        writer=csv.writer(outfile)
        writer.writerows(mylist[1:])
        a+=1
os.chdir('convShaper2_cerberus')
p=os.listdir()
c=0
for i in range(len(p)):
    try:
        os.chdir(p[c])
        c=c+1
        convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convShaper2_convSrc3')
p=os.listdir()
d=0
for i in range(len(p)):
    try:
        os.chdir(p[d])
        d+=1
        convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')

os.chdir('..')
os.chdir('convSrc3_cerberus')

p=os.listdir()
e=0
for i in range(len(p)):
    try:
        os.chdir(p[e])
        e+=1
        convers()
    except NotADirectoryError:
        pass
    except FileNotFoundError:
        pass
    os.chdir('..')
print("INFO: Done with the calculations, check results in the respective directories\n\nINFO: Now creating the graphs...\n")
    